# 生产环境配置
app:
  name: "Boniu Crawler"
  version: "1.0.0"
  environment: "production"
  debug: false

crawler:
  timeout: 60
  retries: 5
  retry_delay: 2
  max_concurrent: 3

boniu:
  base_url: "https://bbs.boniu123.cc"
  forum_url: "https://bbs.boniu123.cc/forum-89-1.html"
  timeout: 60
  retries: 5
  retry_delay: 2

logging:
  level: "INFO"
  file: "./logs/crawler.log"
  rotation: "1 day"
  retention: "30 days"

storage:
  output_dir: "./data/exports"
  format: "json"
  filename: "boniu_forum_posts"

anti_crawler:
  enabled: true
  random_delay: true
  delay_range: [2, 5]
  rotate_user_agents: true

proxy:
  enabled: false
  host: null
  port: null
